### PR TITLE
Refactor minibenchmark Snakemake workflows

### PR DESCRIPTION
**Pull request by pawel-czyz**
This PR refactors the way we do benchmarks, so that they use modular components.

### CODE REVIEW

**Comment by grfrederic** [comment]
great work! i really like how this looks, i think we'll be able to create all our figures efficiently with this :)

**Comment by pawel-czyz** [comment]
> great work! i really like how this looks, i think we'll be able to create all our figures efficiently with this :)

Should we merge it now? It's 8 files already and I think refactoring sparsity deserves its own PR (as we may want to introduce the new method of generating matrices).

**Comment by grfrederic** [comment]
sure, let's

**Review by grfrederic — APPROVED** [review]
wonderful!

**Pull request merged**
